<a href="https://colab.research.google.com/github/nivetha-240901071/python-programing-using-machine-learning/blob/main/240901071_Numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,4,6,4])
print(arr)
x=np.where(arr==4)
print(x)

[1 2 3 4 5 4 6 4]
(array([3, 5, 7]),)


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [ ]:
arr=np.array([3,2,0,1])
print("\noriginal array:",arr)
print("\nsorted array:",np.sort(arr))
arr=np.array([[3,2,4],[5,0,1]])
print("\noriginal array:\n",arr)
print("\nsorted array:\n",np.sort(arr))


original array: [3 2 0 1]

sorted array: [0 1 2 3]

original array:
 [[3 2 4]
 [5 0 1]]

sorted array:
 [[2 3 4]
 [0 1 5]]


In [ ]:
import numpy as np
sorted_array=np.array([1,3,5,7])
values=[2,4,6]
insert_indices=np.searchsorted(sorted_array,values)
print(sorted_array)
print(values)
print(insert_indices)

[1 3 5 7]
[2, 4, 6]
[1 2 3]


In [ ]:
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print("\noriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)


original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]


In [ ]:
import numpy as np
arr=np.array([41,42,43,44])
filter_arr=arr > 42
newarr=arr[filter_arr]
print("\noriginal array:\n",arr)
print("Filter array:condition > 42:\n",filter_arr)
print("Filter array:\n",newarr)


original array:
 [41 42 43 44]
Filter array:condition > 42:
 [False False  True  True]
Filter array:
 [43 44]
