<a href="https://colab.research.google.com/github/nivetha-240901071/python-programing-using-machine-learning/blob/main/240901071_Numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("original array")
print(a)
print(b)
print("\nvector addition")
print(a+b)
print("\nvector subtraction")
print(a-b)
print("\nvector multiplication")
print(a*b)
print("\nvector division")
print(a/b)
print("\nvector dot product")
print(a.dot(b))
print("\nscalar multiplication")
sclr=5
print("scaler value=",sclr)
print("array=",a)
print("result=",a*sclr)
def my_func(x,y):
    if x>y:
       return x-y
    else:
       return x-y
arr1=[10,4,20]
arr2=[2,3,30]
vec_func=np.vectorize(my_func)
print("array 1:",arr1)
print("array 2:",arr2)
print("result:",vec_func(arr1,arr2))

original array
[10 20 30 40 50]
[ 2  4  5  8 10]

vector addition
[12 24 35 48 60]

vector subtraction
[ 8 16 25 32 40]

vector multiplication
[ 20  80 150 320 500]

vector division
[5. 5. 6. 5. 5.]

vector dot product
1070

scalar multiplication
scaler value= 5
array= [10 20 30 40 50]
result= [ 50 100 150 200 250]
array 1: [10, 4, 20]
array 2: [2, 3, 30]
result: [  8   1 -10]
