<a href="https://colab.research.google.com/github/nivetha-240901071/python-programing-using-machine-learning/blob/main/Numpy_basics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([[1,2,3,]])
print("Array created:\n",a)

Array created:
 [[1 2 3]]


In [3]:
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.63456949 0.92648326]
 [0.8695886  0.06099934]]


In [4]:
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
c=np.full((3,3),6)
print("array with all 6s:\n",c)

array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [6]:
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.17584062 0.98329927]
 [0.89903079 0.80224457]]


In [7]:
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [8]:
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\noriginal array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]
