<a href="https://colab.research.google.com/github/nivetha-240901071/python-programing-using-machine-learning/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([[1,2,3],[5,8,7]])
print("Array created:\n",a)

Array created:
 [[1 2 3]
 [5 8 7]]


In [2]:
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.13279796 0.79358642]
 [0.70061586 0.05996763]]


In [3]:
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
c=np.full((3,3),6)
print("array with all 6S:\n",c)

array with all 6S:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [5]:
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [6]:
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\noriginal array:\n",arr)
print("reshaped array[4,3]:\n",newarr)


original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [7]:
flarr=arr.flatten()
print("\nOriginal Array:\n",arr)
print("\nFlattened Array:\n",flarr)


Original Array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

Flattened Array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [8]:
print("\nno of dimensions:\n",arr.ndim)
print("\nshape of array:\n",arr.shape)
print("\nsize of array:\n",arr.size)
print("\narray type:\n",arr.dtype)
newtype=arr.astype('f')
print("\nconverted array element:\n",newtype)
print("\nconverted array type:\n",newtype.dtype)


no of dimensions:
 2

shape of array:
 (3, 4)

size of array:
 12

array type:
 int64

converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

converted array type:
 float32


In [9]:
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2,0:2])
print(p[2:,2:])
print(p[3:,3:])
print(p[:,1])
c=p.astype('f')
print(c)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8]
[[ 9]
 [12]
 [15]]
[]
[ 2  5  8 11 14]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
