<a href="https://colab.research.google.com/github/nivetha-240901071/python-programing-using-machine-learning/blob/main/Numpy_basics_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
arr=np.array([[1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2]])
print("original array:\n",arr)

original array:
 [[ 1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [7]:
print("Every other row:\n",arr[0:3:2])

Every other row:
 [[1.  2.  0.  4. ]
 [2.6 0.  7.  8. ]]


In [8]:
arr=np.array([1,2,3,4,5,6,7])
print("original array:\n",arr)
print("Return every other element in the array:arr[::2]:",arr[::2])

original array:
 [1 2 3 4 5 6 7]
Return every other element in the array:arr[::2]: [1 3 5 7]


In [9]:
arr=np.array([[1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2]])
temp=arr[:2,:3]
print("\n Array with first 2 rows and 3 column:\n",temp)


 Array with first 2 rows and 3 column:
 [[ 1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [10]:
newarr=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices (0,3),(1,2),(2,1),(3,0):\n",newarr)


Elements at indices (0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]


In [11]:
cond=arr>2
temp=arr[cond]
print("Elements greater than 2:\n",temp)

Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [12]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([1,5,6])
arr3=np.hstack((arr1,arr2))
print(arr3)

[1 2 3 1 5 6]


In [13]:
arr4=np.vstack((arr1,arr2))
print(arr4)

[[1 2 3]
 [1 5 6]]


In [14]:
arr5=np.dstack((arr1,arr2))
print(arr5)

[[[1 1]
  [2 5]
  [3 6]]]


In [15]:
arr=np.array([1,2,3,4,5,6])
arr6=np.array_split(arr,3)
print(arr)
print(arr6)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
